[features]
seeds = false
skip-lint = false
[programs.localnet]
election = "EMh4zLtsitGMJ7wxJdY4xFkDqJHiTor91chN5nmB9JLB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\acer\\.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
